packages:
  - apps/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - ts-jest@29.4.12
